version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: 'Dockerfile'
    container_name: 'mongo-auth-api'
    ports:
      - '${PORT:-3000}:3000'
    environment:
      MONGO_URI: '${MONGO_URI}'
      JWT_SECRET: '${JWT_SECRET}'
    depends_on:
      - 'mongodb'

  mongodb:
    image: 'mongo:latest'
    container_name: 'mongo-auth-db'
    restart: 'always'
    ports:
      - '27018:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: